includes += -Ilib/libc

objs += lib/libc/__ctype_b_loc.o
objs += lib/libc/memchr.o
objs += lib/libc/strcat.o
objs += lib/libc/strcmp.o
objs += lib/libc/strcpy.o
objs += lib/libc/strlcpy.o
objs += lib/libc/strlen.o
objs += lib/libc/strncat.o
objs += lib/libc/strncmp.o
objs += lib/libc/strncpy.o
objs += lib/libc/strnlen.o
objs += lib/libc/strstr.o
objs += lib/libc/strtoul.o
